### ISSUE TITLE
[Feature request] Add parameter to bring app to focus

### ISSUE THREAD

**Issue by gpunktschmitz** [Merrit/feeling_finder#110]
I am starting the app using flatpak on linux

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=feeling_finder codes.merritt.FeelingFinder &>/dev/null &`

I'd like to add another keyboard shortcut to bring it to focus because for some reasons the integrated `Alt + .` is not always working for me (could not yet figure out why this is).

**Comment by Merrit** [comment]
Do you mean that if the window is already visible but not focused, it isn't becoming focused the way you'd expect?

**Comment by gpunktschmitz** [comment]
yes. I launch the app at startup using the command mentioned. it is running in the tray and using the mouse (right-click -> show) I can use it. but the app does not come to focus when pressing `ALT + .` that's why I want to add `Mod4 + .` to "launch" the app again - with a parameter telling it to look for an instance running and bringing that to focus.

**Comment by Merrit** [comment]
Great, thanks for clarifying! I will look into it and see what can be done.

**Comment by Merrit** [comment]
I've made a change so that starting the app when it is already running will cause the existing version to toggle show/hide.

Now you can just set a shortcut in the system that launches the app, and once the app is running that shortcut will toggle visibility.

Here is an alpha build if you'd like to give it a try:

[FeelingFinder-Linux-Portable.tar.gz](https://github.com/user-attachments/files/17034778/FeelingFinder-Linux-Portable.tar.gz)

**Comment by gpunktschmitz** [comment]
unfortunately it is not working as expected. the app flickers for a second when running the second time. seems like it is toggled twice - first visible then hidden to tray again.

I had to install `libkeybinder-3.0-0` first - afterwards the alpha worked. however `alt + .` also with the alpha does not bring it to focus. and just like the flatpak version installed - when I right-click the tray icon and select "show" the app opens in the background and has to be selected from the taskbar to bring it to the front.

**Comment by Merrit** [comment]
Even better way to use this new toggle is to create a custom shortcut that calls the dbus method directly:

```
dbus-send --session --print-reply --dest=codes.merritt.FeelingFinder / codes.merritt.FeelingFinder.toggleWindow
```

.. which can also be tested easily from a terminal.

Sounds like that still might not solve your issue though. Feels like perhaps an issue with your system somehow, given your description of the odd behaviour. What is your Linux distro/version/desktop environment?

**Comment by gpunktschmitz** [comment]
running this very command (from terminal) works just fine. also binding it to a hotkey does. 👌

strangely enough also now running the very same alpha version again does bring the to the front - it does still flicker - but at the end now the app gets shown. whereas the `dbus-send`-command acts more - instant.

I am running Linux Mint 21.3 MATE edition which had pending updates (they where installed but not restarted) when testing previously - maybe that caused the flickering-but-not-showing-issue? 🤷‍♂️

**Comment by Merrit** [comment]
Great to hear the dbus command works well!

As far as the built-in hotkey goes, getting it in a good state for Linux will probably require writing a system-wide hotkey library - so that's a bit on the back burner.

Do you feel like this new dbus method of toggling the window solves your issue until then? If so I can document that as an alternative for Linux users until I can fix up a built-in solution.

**Comment by gpunktschmitz** [comment]
it sure does resolve my issue. I am super happy using the dbus command with a custom shortcut.

thanks alot!

**Comment by Merrit** [comment]
Great! Thanks for opening the issue, and working with me to resolve it :tada: :blue_heart:

**Comment by Merrit** [comment]
Added in-app documentation for this new feature:

![image](https://github.com/user-attachments/assets/1d4cde31-d40e-4ac2-b6fe-16402c0749c7)

Live in v1.8.0, releasing now. :)
