### ISSUE TITLE
provide alternate skintone emojis

### ISSUE THREAD

**Issue by rio-codes** [Merrit/feeling_finder#54]
This app is wonderful, and very easy to use. The only issue I have encountered is that there are no alternate skintone emojis. It looks like there is a unicode modifier to add for each skintone: https://unicode.org/emoji/charts/full-emoji-modifiers.html#1f44b_1f3fb Would this be difficult to implement?

**Comment by Merrit** [comment]
Hi, thanks for the issue! I will look into it. :smiley:

**Comment by Merrit** [comment]
This looks doable, I am looking into an implementation now. :zap:

**Comment by Merrit** [comment]
I've added support for variants / skin tones as of [1.0.0](https://github.com/Merrit/feeling_finder/releases/tag/v1.0.0). 🎉

The update should be live on Flathub soon. I'd love to hear your feedback on this feature!

![Screenshot of the new skin tone picker](https://user-images.githubusercontent.com/9575627/240424548-bda1bb27-27ee-4e57-b344-cc753f7cb4a0.png)

Also, I noticed you had sponsored me on GitHub. Thank you so much! I really appreciate it. 😊 Thanks for helping me make free software! 💙

**Comment by rio-codes** [comment]
Hi Kristen,

This is amazing!! It worked flawlessly. 🙌🏾 Thank you so much. I
noticed you use Dart, I have never even heard of that language. 🤯 Is
it difficult to learn? I am only familiar with Python, a bit of
Javascript and CSS, and (unfortunately) Powershell.

Anyway, thanks again, let me know if I can contribute to any of your
projects in any way. 🫶🏾

Warmly,

Rio

**Comment by Merrit** [comment]
Hey Rio, so glad to hear it is working for you! :tada: 

I love Dart, it is what finally clicked for me in trying to learn programming! I found it much easier to learn than either JavaScript or Python; I found their dynamic types led me to a lot of errors and confusing issues, while Dart has specific types so instead of 

```python
variants = emoji.variants
```

and possibly wondering what the heck `variants` was supposed to be, Dart goes more like

```dart
List<Emoji> variants = emoji.variants;
```

To each their own for sure, but Dart runs on every platform (Desktop, Web, Mobile, Embedded), writes great GUI software thanks to [Flutter](https://flutter.dev/), and has been one of the fastest growing languages/frameworks for years, so I don't think I am alone in liking it! :grinning: The autocomplete suggestions, docs, and built-in tooling/helpers alone are awesome at making programming easier to wrestle with IMHO. I heartily suggest it if you are interested!

If you'd like to contribute, there are always a myriad of things that need doing in all my projects that I never have enough time/energy for! Things like better app icon that didn't take 2 minutes to throw together (like this app!), improved descriptions for the README / store pages, translations, improved/any website, unit tests, refactoring, etc... :sweat_smile: So lots of opportunities, whether coding or non-coding! :muscle: 

Thanks again for raising this issue, definitely think the app is better for it now! 💙
